version: "3"

services:
  app:
    image: dashiro-app:latest
    container_name: dashiro-app
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - /app/node_modules
    environment:
      NODE_ENV: "production"
      REACT_APP_VERSION: "v1.1.0"
      GENERATE_SOURCEMAP: "false"