version: "3"

services:
  app:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    environment:
      NODE_ENV: production
    command: npm start